---
- name: Install fun packages
  hosts: Arimova
  become: yes

  tasks:
    - name: Ensure cmatrix is installed
      ansible.builtin.package:
        name: cmatrix
        state: present

    - name: Ensure cowsay is installed
      ansible.builtin.package:
        name: cowsay
        state: present

    - name: Ensure sl is installed
      ansible.builtin.package:
        name: sl
        state: present
